package com.vantiv.services.merchant.payments.v6;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-07-31T13:47:48.527-06:00
 * Generated source version: 3.0.1
 * 
 */
@WebServiceClient(name = "PaymentPortTypeService", 
                  wsdlLocation = "https://ws-cert.vantiv.com/merchant/payments-cert/v6?wsdl",
                  targetNamespace = "urn:com:vantiv:services:merchant:payments:v6") 
public class PaymentPortTypeService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:com:vantiv:services:merchant:payments:v6", "PaymentPortTypeService");
    public final static QName PaymentPortTypeSoap11 = new QName("urn:com:vantiv:services:merchant:payments:v6", "PaymentPortTypeSoap11");
    static {
        URL url = null;
        try {
            url = new URL("https://ws-cert.vantiv.com/merchant/payments-cert/v6?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PaymentPortTypeService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "https://ws-cert.vantiv.com/merchant/payments-cert/v6?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PaymentPortTypeService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PaymentPortTypeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PaymentPortTypeService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns PaymentPortType
     */
    @WebEndpoint(name = "PaymentPortTypeSoap11")
    public PaymentPortType getPaymentPortTypeSoap11() {
        return super.getPort(PaymentPortTypeSoap11, PaymentPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PaymentPortType
     */
    @WebEndpoint(name = "PaymentPortTypeSoap11")
    public PaymentPortType getPaymentPortTypeSoap11(WebServiceFeature... features) {
        return super.getPort(PaymentPortTypeSoap11, PaymentPortType.class, features);
    }

}
