package com.vantiv.services.merchant.payments.v6;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-07-31T13:47:48.519-06:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "urn:com:vantiv:services:merchant:payments:v6", name = "PaymentPortType")
@XmlSeeAlso({com.vantiv.types.payment.transactions.v6.ObjectFactory.class, com.vantiv.types.payment.systems.v6.ObjectFactory.class, com.vantiv.types.common.v6.ObjectFactory.class, com.vantiv.types.payment.instruments.v6.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PaymentPortType {

    @WebResult(name = "AuthorizeResponse", targetNamespace = "urn:com:vantiv:types:payment:transactions:v6", partName = "AuthorizeResponse")
    @WebMethod(operationName = "Authorize")
    public com.vantiv.types.payment.transactions.v6.AuthorizeResponse authorize(
        @WebParam(partName = "AuthorizeRequest", name = "AuthorizeRequest", targetNamespace = "urn:com:vantiv:types:payment:transactions:v6")
        com.vantiv.types.payment.transactions.v6.AuthorizeRequest authorizeRequest
    ) throws ServerFault, RequestValidationFault;

    @WebResult(name = "UnloadResponse", targetNamespace = "urn:com:vantiv:types:payment:transactions:v6", partName = "UnloadResponse")
    @WebMethod(operationName = "Unload")
    public com.vantiv.types.payment.transactions.v6.UnloadResponse unload(
        @WebParam(partName = "UnloadRequest", name = "UnloadRequest", targetNamespace = "urn:com:vantiv:types:payment:transactions:v6")
        com.vantiv.types.payment.transactions.v6.UnloadRequest unloadRequest
    ) throws ServerFault, RequestValidationFault;

    @WebResult(name = "BalanceInquiryResponse", targetNamespace = "urn:com:vantiv:types:payment:transactions:v6", partName = "BalanceInquiryResponse")
    @WebMethod(operationName = "BalanceInquiry")
    public com.vantiv.types.payment.transactions.v6.BalanceInquiryResponse balanceInquiry(
        @WebParam(partName = "BalanceInquiryRequest", name = "BalanceInquiryRequest", targetNamespace = "urn:com:vantiv:types:payment:transactions:v6")
        com.vantiv.types.payment.transactions.v6.BalanceInquiryRequest balanceInquiryRequest
    ) throws ServerFault, RequestValidationFault;

    @WebResult(name = "CaptureResponse", targetNamespace = "urn:com:vantiv:types:payment:transactions:v6", partName = "CaptureResponse")
    @WebMethod(operationName = "Capture")
    public com.vantiv.types.payment.transactions.v6.CaptureResponse capture(
        @WebParam(partName = "CaptureRequest", name = "CaptureRequest", targetNamespace = "urn:com:vantiv:types:payment:transactions:v6")
        com.vantiv.types.payment.transactions.v6.CaptureRequest captureRequest
    ) throws ServerFault, RequestValidationFault;

    @WebResult(name = "AdjustResponse", targetNamespace = "urn:com:vantiv:types:payment:transactions:v6", partName = "AdjustResponse")
    @WebMethod(operationName = "Adjust")
    public com.vantiv.types.payment.transactions.v6.AdjustResponse adjust(
        @WebParam(partName = "AdjustRequest", name = "AdjustRequest", targetNamespace = "urn:com:vantiv:types:payment:transactions:v6")
        com.vantiv.types.payment.transactions.v6.AdjustRequest adjustRequest
    ) throws ServerFault, RequestValidationFault;

    @WebResult(name = "PurchaseResponse", targetNamespace = "urn:com:vantiv:types:payment:transactions:v6", partName = "PurchaseResponse")
    @WebMethod(operationName = "Purchase")
    public com.vantiv.types.payment.transactions.v6.PurchaseResponse purchase(
        @WebParam(partName = "PurchaseRequest", name = "PurchaseRequest", targetNamespace = "urn:com:vantiv:types:payment:transactions:v6")
        com.vantiv.types.payment.transactions.v6.PurchaseRequest purchaseRequest
    ) throws ServerFault, RequestValidationFault;

    @WebResult(name = "EchoResponse", targetNamespace = "urn:com:vantiv:types:payment:transactions:v6", partName = "EchoResponse")
    @WebMethod(operationName = "Echo")
    public com.vantiv.types.payment.transactions.v6.EchoResponse echo(
        @WebParam(partName = "EchoRequest", name = "EchoRequest", targetNamespace = "urn:com:vantiv:types:payment:transactions:v6")
        com.vantiv.types.payment.transactions.v6.EchoRequest echoRequest
    ) throws ServerFault, RequestValidationFault;

    @WebResult(name = "ActivateResponse", targetNamespace = "urn:com:vantiv:types:payment:transactions:v6", partName = "ActivateResponse")
    @WebMethod(operationName = "Activate")
    public com.vantiv.types.payment.transactions.v6.ActivateResponse activate(
        @WebParam(partName = "ActivateRequest", name = "ActivateRequest", targetNamespace = "urn:com:vantiv:types:payment:transactions:v6")
        com.vantiv.types.payment.transactions.v6.ActivateRequest activateRequest
    ) throws ServerFault, RequestValidationFault;

    @WebResult(name = "CloseBatchResponse", targetNamespace = "urn:com:vantiv:types:payment:transactions:v6", partName = "CloseBatchResponse")
    @WebMethod(operationName = "CloseBatch")
    public com.vantiv.types.payment.transactions.v6.CloseBatchResponse closeBatch(
        @WebParam(partName = "CloseBatchRequest", name = "CloseBatchRequest", targetNamespace = "urn:com:vantiv:types:payment:transactions:v6")
        com.vantiv.types.payment.transactions.v6.CloseBatchRequest closeBatchRequest
    ) throws ServerFault, RequestValidationFault;

    @WebResult(name = "UpdateCardResponse", targetNamespace = "urn:com:vantiv:types:payment:transactions:v6", partName = "UpdateCardResponse")
    @WebMethod(operationName = "UpdateCard")
    public com.vantiv.types.payment.transactions.v6.UpdateCardResponse updateCard(
        @WebParam(partName = "UpdateCardRequest", name = "UpdateCardRequest", targetNamespace = "urn:com:vantiv:types:payment:transactions:v6")
        com.vantiv.types.payment.transactions.v6.UpdateCardRequest updateCardRequest
    ) throws ServerFault, RequestValidationFault;

    @WebResult(name = "BatchBalanceResponse", targetNamespace = "urn:com:vantiv:types:payment:transactions:v6", partName = "BatchBalanceResponse")
    @WebMethod(operationName = "BatchBalance")
    public com.vantiv.types.payment.transactions.v6.BatchBalanceResponse batchBalance(
        @WebParam(partName = "BatchBalanceRequest", name = "BatchBalanceRequest", targetNamespace = "urn:com:vantiv:types:payment:transactions:v6")
        com.vantiv.types.payment.transactions.v6.BatchBalanceRequest batchBalanceRequest
    ) throws ServerFault, RequestValidationFault;

    @WebResult(name = "ReloadResponse", targetNamespace = "urn:com:vantiv:types:payment:transactions:v6", partName = "ReloadResponse")
    @WebMethod(operationName = "Reload")
    public com.vantiv.types.payment.transactions.v6.ReloadResponse reload(
        @WebParam(partName = "ReloadRequest", name = "ReloadRequest", targetNamespace = "urn:com:vantiv:types:payment:transactions:v6")
        com.vantiv.types.payment.transactions.v6.ReloadRequest reloadRequest
    ) throws ServerFault, RequestValidationFault;

    @WebResult(name = "RefundResponse", targetNamespace = "urn:com:vantiv:types:payment:transactions:v6", partName = "RefundResponse")
    @WebMethod(operationName = "Refund")
    public com.vantiv.types.payment.transactions.v6.RefundResponse refund(
        @WebParam(partName = "RefundRequest", name = "RefundRequest", targetNamespace = "urn:com:vantiv:types:payment:transactions:v6")
        com.vantiv.types.payment.transactions.v6.RefundRequest refundRequest
    ) throws ServerFault, RequestValidationFault;

    @WebResult(name = "TokenizeResponse", targetNamespace = "urn:com:vantiv:types:payment:transactions:v6", partName = "TokenizeResponse")
    @WebMethod(operationName = "Tokenize")
    public com.vantiv.types.payment.transactions.v6.TokenizeResponse tokenize(
        @WebParam(partName = "TokenizeRequest", name = "TokenizeRequest", targetNamespace = "urn:com:vantiv:types:payment:transactions:v6")
        com.vantiv.types.payment.transactions.v6.TokenizeRequest tokenizeRequest
    ) throws ServerFault, RequestValidationFault;

    @WebResult(name = "CancelResponse", targetNamespace = "urn:com:vantiv:types:payment:transactions:v6", partName = "CancelResponse")
    @WebMethod(operationName = "Cancel")
    public com.vantiv.types.payment.transactions.v6.CancelResponse cancel(
        @WebParam(partName = "CancelRequest", name = "CancelRequest", targetNamespace = "urn:com:vantiv:types:payment:transactions:v6")
        com.vantiv.types.payment.transactions.v6.CancelRequest cancelRequest
    ) throws ServerFault, RequestValidationFault;

    @WebResult(name = "CloseResponse", targetNamespace = "urn:com:vantiv:types:payment:transactions:v6", partName = "CloseResponse")
    @WebMethod(operationName = "Close")
    public com.vantiv.types.payment.transactions.v6.CloseResponse close(
        @WebParam(partName = "CloseRequest", name = "CloseRequest", targetNamespace = "urn:com:vantiv:types:payment:transactions:v6")
        com.vantiv.types.payment.transactions.v6.CloseRequest closeRequest
    ) throws ServerFault, RequestValidationFault;
}
