
package com.vantiv.services.merchant.payments.v6;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-07-31T13:47:48.463-06:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "ServerFault", targetNamespace = "urn:com:vantiv:types:payment:transactions:v6")
public class ServerFault extends Exception {
    
    private com.vantiv.types.payment.transactions.v6.ServerFault serverFault;

    public ServerFault() {
        super();
    }
    
    public ServerFault(String message) {
        super(message);
    }
    
    public ServerFault(String message, Throwable cause) {
        super(message, cause);
    }

    public ServerFault(String message, com.vantiv.types.payment.transactions.v6.ServerFault serverFault) {
        super(message);
        this.serverFault = serverFault;
    }

    public ServerFault(String message, com.vantiv.types.payment.transactions.v6.ServerFault serverFault, Throwable cause) {
        super(message, cause);
        this.serverFault = serverFault;
    }

    public com.vantiv.types.payment.transactions.v6.ServerFault getFaultInfo() {
        return this.serverFault;
    }
}
